# name: Android Release

# # 1
# on:
#   # 2
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # 3
#   workflow_dispatch:

# # 4
# jobs:
#   # 5
#   build:
#     # 6
#     runs-on: ubuntu-latest

#     # 7
#     steps:
#       # 8
#       - uses: actions/checkout@v3
#       # 9
#       - uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: "12.x"
#           cache: 'gradle'
#       # 10
#       - uses: subosito/flutter-action@v2
#         with:
#           # 11
#           flutter-version: "3.3.0"
#           channel: 'stable'
#           cache: true
#       # 12
#       - name: Flutter upgrade
#         run: flutter upgrade --force
#       # 13
#       - name: Get dependencies
#         run: flutter pub get

#       #14 Runs a set of commands using the runners shell
#       - name: Start APK build
#         run: flutter build apk
#       - uses: actions/upload-artifact@v1
#         with:
#           name: release-apk
#           path: build/app/outputs/apk/release/app-release.apk

name: Android Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Updated to latest version

      - uses: actions/setup-java@v4  # Updated to latest version
        with:
          distribution: 'zulu'
          java-version: "12"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0"
          channel: 'stable'
          cache: true

      - name: Flutter upgrade
        run: flutter upgrade --force

      - name: Get dependencies
        run: flutter pub get

      - name: Start APK build
        run: flutter build apk

      # ✅ Updated to actions/upload-artifact@v4
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
